###  Created by Luis A. Sanchez-Perez (alejand@umich.edu).
<p><span style="color:green"><b>Copyright &#169;</b> Do not distribute or use without authorization from author.</span></p>

In [1]:
import tensorflow as tf
import sys
sys.path.append('../extraction/')
from air_four_classes_temporal_cnn import create_dataset
from utils import display_performance

### 1. Create dataset

In [2]:
# Data location
train_records = '../exports/2020-02-07 01-09-35/train.tfrecord'
test_records = '../exports/2020-02-07 01-09-35/test.tfrecord'

In [3]:
train_ds, test_ds = create_dataset(train_records, test_records)

### 2. Load model

In [4]:
model = tf.keras.models.load_model('trained_model/air_four_classes_temporal_cnn/')

In [5]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 401, 128)]        0         
_________________________________________________________________
conv1d (Conv1D)              (None, 51, 16)            32784     
_________________________________________________________________
dropout (Dropout)            (None, 51, 16)            0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 51, 16)            784       
_________________________________________________________________
dropout_1 (Dropout)          (None, 51, 16)            0         
_________________________________________________________________
global_max_pooling1d (Global (None, 16)                0         
_________________________________________________________________
dense (Dense)                (None, 4)                 68    

### 3. Evaluate model

In [6]:
model.evaluate(train_ds)

     14/Unknown - 2s 157ms/step - loss: 0.0683 - accuracy: 0.9989

[0.06832758736397539, 0.99885845]

In [7]:
model.evaluate(test_ds)

      1/Unknown - 0s 91ms/step - loss: 0.3390 - accuracy: 0.9118

[0.3390328586101532, 0.9117647]

In [8]:
display_performance(model, train_ds, test_ds)


------- Training --------
Confusion Matrix:
[[324   0   0   0]
 [  0 215   1   0]
 [  0   0 180   0]
 [  0   0   0 156]]

Accuracy: 0.9989
Precision: 0.9986
Recall: 0.9988
F1 Score: 0.9987

--------- Test ----------
Confusion Matrix:
[[12  0  0  0]
 [ 0  8  1  0]
 [ 0  0  7  0]
 [ 0  0  2  4]]

Accuracy: 0.9118
Precision: 0.9250
Recall: 0.8889
F1 Score: 0.9066
