###  Created by Luis A. Sanchez-Perez (alejand@umich.edu).
<p><span style="color:green"><b>Copyright &#169;</b> Do not distribute or use without authorization from author.</span></p>

In [1]:
import tensorflow as tf
import sys
sys.path.append('../extraction/')
from air_four_classes_rnn import create_dataset
from utils import display_performance

### 1. Create dataset

In [2]:
# Data location
train_records = '../exports/2020-02-07 01-09-35/train.tfrecord'
test_records = '../exports/2020-02-07 01-09-35/test.tfrecord'

In [3]:
train_ds, test_ds = create_dataset(train_records, test_records, sequencer=True)

### 2. Load model

In [4]:
model = tf.keras.models.load_model('trained_model/air_four_classes_rnn/')

In [5]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 128, 401, 1)]     0         
_________________________________________________________________
Sequencer (SpecSequencer)    multiple                  0         
_________________________________________________________________
Conv1 (TimeDistributed)      multiple                  832       
_________________________________________________________________
Pool1 (TimeDistributed)      multiple                  0         
_________________________________________________________________
Conv2 (TimeDistributed)      multiple                  25632     
_________________________________________________________________
Conv3 (TimeDistributed)      multiple                  25632     
_________________________________________________________________
Pool2 (TimeDistributed)      multiple                  0     

### 3. Evaluate model

In [6]:
model.evaluate(train_ds)

     14/Unknown - 3s 244ms/step - loss: 0.0486 - accuracy: 1.0000

[0.04860168110047068, 1.0]

In [7]:
model.evaluate(test_ds)

      1/Unknown - 0s 364ms/step - loss: 0.2609 - accuracy: 0.9706

[0.26092472672462463, 0.9705882]

In [8]:
display_performance(model, train_ds, test_ds)


------- Training --------
Confusion Matrix:
[[324   0   0   0]
 [  0 216   0   0]
 [  0   0 180   0]
 [  0   0   0 156]]

Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000

--------- Test ----------
Confusion Matrix:
[[12  0  0  0]
 [ 0  8  1  0]
 [ 0  0  7  0]
 [ 0  0  0  6]]

Accuracy: 0.9706
Precision: 0.9688
Recall: 0.9722
F1 Score: 0.9705
