###  Created by Luis A. Sanchez-Perez (alejand@umich.edu).
<p><span style="color:green"><b>Copyright &#169;</b> Do not distribute or use without authorization from author.</span></p>

In [1]:
import tensorflow as tf
import sys
sys.path.append('../extraction/')
sys.path.append('../models/')
from air_four_classes_rnn import create_dataset
from utils import display_performance
from commons import get_classes_from_directory

### 1. Create dataset

In [2]:
# Data location
folder = '../exports/2020-02-07 01-09-35 (four classes)/'

In [3]:
# Finding categories in the folder
classes = get_classes_from_directory(folder)
classes

[b'A320-2xx (CFM56-5)',
 b'B737-7xx (CF56-7B22-)',
 b'B737-8xx (CF56-7B22+)',
 b'ERJ190 (CF34-10E)']

In [4]:
train_ds, test_ds = create_dataset(folder, classes)

### 2. Load model

In [5]:
model = tf.keras.models.load_model(folder +
                                   'experiments/2020-07-02 00-29-42/' +
                                   'trained_model/air_four_classes_rnn/')

In [6]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 128, 401, 1)]     0         
_________________________________________________________________
Sequencer (SpectrogamSequenc multiple                  0         
_________________________________________________________________
Conv1 (TimeDistributed)      multiple                  832       
_________________________________________________________________
Pool1 (TimeDistributed)      multiple                  0         
_________________________________________________________________
Conv2 (TimeDistributed)      multiple                  25632     
_________________________________________________________________
Conv3 (TimeDistributed)      multiple                  25632     
_________________________________________________________________
Pool2 (TimeDistributed)      multiple                  0     

### 3. Evaluate model

In [7]:
model.evaluate(train_ds)

     14/Unknown - 3s 243ms/step - loss: 0.0401 - accuracy: 1.0000

[0.04014420376292297, 1.0]

In [8]:
model.evaluate(test_ds)

      1/Unknown - 0s 366ms/step - loss: 0.2309 - accuracy: 0.9706

[0.23090919852256775, 0.9705882]

In [9]:
display_performance(model, train_ds, test_ds)


------- Training --------
Confusion Matrix:
[[324   0   0   0]
 [  0 216   0   0]
 [  0   0 156   0]
 [  0   0   0 180]]

Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000

--------- Test ----------
Confusion Matrix:
[[12  0  0  0]
 [ 0  8  0  1]
 [ 0  0  6  0]
 [ 0  0  0  7]]

Accuracy: 0.9706
Precision: 0.9688
Recall: 0.9722
F1 Score: 0.9705
