###  Created by Luis A. Sanchez-Perez (alejand@umich.edu).
<p><span style="color:green"><b>Copyright &#169;</b> Do not distribute or use without authorization from author.</span></p>

In [1]:
import tensorflow as tf
import pathlib
import sys
sys.path.append('../models/')
sys.path.append('../extraction/')
from air_multiclass_rnn import create_dataset
from commons import get_classes_from_directory
from utils import display_performance

### 1. Create dataset

In [2]:
# Data location
folder = pathlib.Path('../exports/2020-03-01 07-34-19 (eight classes)/')

In [3]:
# Finding categories in the folder
classes = get_classes_from_directory(folder)
classes

[b'A319-1xx (V25xx)',
 b'A320-2xx (CFM56-5)',
 b'A320-2xx (V25xx)',
 b'B737-7xx (CF56-7B22-)',
 b'B737-8xx (CF56-7B22+)',
 b'ERJ145 (AE3007)',
 b'ERJ170-175 (CF34-8E)',
 b'ERJ190 (CF34-10E)']

In [4]:
train_ds, test_ds = create_dataset(folder, classes)

### 2. Load model

In [5]:
model = tf.keras.models.load_model(
    str(folder / 'experiments/2020-07-02-14-17-00/' / 'trained_model/air_multiclass_rnn/')
)
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 128, 401, 1)]     0         
_________________________________________________________________
Sequencer (SpectrogamSequenc multiple                  0         
_________________________________________________________________
time_distributed (TimeDistri multiple                  832       
_________________________________________________________________
Relu1 (Activation)           multiple                  0         
_________________________________________________________________
time_distributed_1 (TimeDist multiple                  0         
_________________________________________________________________
time_distributed_2 (TimeDist multiple                  25632     
_________________________________________________________________
Relu2 (Activation)           multiple                  0     

### 3. Evaluate model

In [6]:
model.evaluate(train_ds)

     20/Unknown - 4s 182ms/step - loss: 0.1768 - accuracy: 0.9912

[0.17683041617274284, 0.9911859]

In [7]:
model.evaluate(test_ds)

      1/Unknown - 1s 508ms/step - loss: 0.5467 - accuracy: 0.8600

[0.5467047691345215, 0.86]

In [8]:
display_performance(model, train_ds, test_ds)


------- Training --------
Confusion Matrix:
[[ 84   0   0   0   0   0   0   0]
 [  0 324   0   0   0   0   0   0]
 [  0   0  83   0   0   1   0   0]
 [  0   0   0 215   1   0   0   0]
 [  0   0   0   0 156   0   0   0]
 [  0   0   0   0   7 137   0   0]
 [  0   0   0   0   0   0  60   0]
 [  0   0   0   0   1   1   0 178]]

Accuracy: 0.9912
Precision: 0.9914
Recall: 0.9905
F1 Score: 0.9909

--------- Test ----------
Confusion Matrix:
[[ 2  0  0  0  0  1  0  0]
 [ 0 12  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0]
 [ 0  0  0  9  0  0  0  0]
 [ 0  0  0  2  4  0  0  0]
 [ 0  0  0  0  0  4  0  2]
 [ 0  0  0  0  1  0  1  1]
 [ 0  0  0  0  0  0  0  7]]

Accuracy: 0.8600
Precision: 0.8898
Recall: 0.7917
F1 Score: 0.8379


### 2. Load model

In [9]:
model = tf.keras.models.load_model(
    str(folder / 'experiments/2020-07-02-14-24-54/' / 'trained_model/air_multiclass_rnn/')
)
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 128, 401, 1)]     0         
_________________________________________________________________
Sequencer (SpectrogamSequenc multiple                  0         
_________________________________________________________________
time_distributed (TimeDistri multiple                  800       
_________________________________________________________________
BatchNorm1 (BatchNormalizati multiple                  60        
_________________________________________________________________
Relu1 (Activation)           multiple                  0         
_________________________________________________________________
time_distributed_1 (TimeDist multiple                  0         
_________________________________________________________________
time_distributed_2 (TimeDist multiple                  25600 

### 3. Evaluate model

In [10]:
model.evaluate(train_ds)

     20/Unknown - 1s 64ms/step - loss: 0.1072 - accuracy: 1.0000

[0.10721815750002861, 1.0]

In [11]:
model.evaluate(test_ds)

      1/Unknown - 0s 85ms/step - loss: 0.5104 - accuracy: 0.8800

[0.5103955268859863, 0.88]

In [12]:
display_performance(model, train_ds, test_ds)


------- Training --------
Confusion Matrix:
[[ 84   0   0   0   0   0   0   0]
 [  0 324   0   0   0   0   0   0]
 [  0   0  84   0   0   0   0   0]
 [  0   0   0 216   0   0   0   0]
 [  0   0   0   0 156   0   0   0]
 [  0   0   0   0   0 144   0   0]
 [  0   0   0   0   0   0  60   0]
 [  0   0   0   0   0   0   0 180]]

Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1 Score: 1.0000

--------- Test ----------
Confusion Matrix:
[[ 2  0  1  0  0  0  0  0]
 [ 0 12  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0]
 [ 0  0  0  9  0  0  0  0]
 [ 0  0  0  2  4  0  0  0]
 [ 0  0  0  0  0  4  0  2]
 [ 0  0  0  0  1  0  2  0]
 [ 0  0  0  0  0  0  0  7]]

Accuracy: 0.8800
Precision: 0.8995
Recall: 0.8333
F1 Score: 0.8652
