###  Created by Luis A. Sanchez-Perez (alejand@umich.edu).
<p><span style="color:green"><b>Copyright &#169;</b> Do not distribute or use without authorization from author.</span></p>

In [1]:
import tensorflow as tf
import pathlib
import sys
sys.path.append('../extraction/')
sys.path.append('../models/')
from air_multiclass_rnn import create_dataset
from utils import display_performance
from commons import get_classes_from_directory

### 1. Create dataset

In [2]:
# Data location
folder = pathlib.Path('../exports/2020-02-07 01-09-35 (four classes)/')

In [3]:
# Finding categories in the folder
classes = get_classes_from_directory(folder)
classes

[b'A320-2xx (CFM56-5)',
 b'B737-7xx (CF56-7B22-)',
 b'B737-8xx (CF56-7B22+)',
 b'ERJ190 (CF34-10E)']

In [4]:
train_ds, test_ds = create_dataset(folder, classes)

### 2. Load model

In [5]:
model = tf.keras.models.load_model(
    str(folder / 'experiments/2020-07-02-14-07-24/' / 'trained_model/air_multiclass_rnn/')
)
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 128, 401, 1)]     0         
_________________________________________________________________
Sequencer (SpectrogamSequenc multiple                  0         
_________________________________________________________________
time_distributed (TimeDistri multiple                  800       
_________________________________________________________________
BatchNorm1 (BatchNormalizati multiple                  60        
_________________________________________________________________
Relu1 (Activation)           multiple                  0         
_________________________________________________________________
time_distributed_1 (TimeDist multiple                  0         
_________________________________________________________________
time_distributed_2 (TimeDist multiple                  25600 

### 3. Evaluate model

In [6]:
model.evaluate(train_ds)

     14/Unknown - 4s 252ms/step - loss: 0.0406 - accuracy: 0.9989

[0.04056407404797418, 0.99885845]

In [7]:
model.evaluate(test_ds)

      1/Unknown - 0s 377ms/step - loss: 0.2756 - accuracy: 0.9412

[0.2756146192550659, 0.9411765]

In [8]:
display_performance(model, train_ds, test_ds)


------- Training --------
Confusion Matrix:
[[324   0   0   0]
 [  0 216   0   0]
 [  0   0 156   0]
 [  0   0   1 179]]

Accuracy: 0.9989
Precision: 0.9984
Recall: 0.9986
F1 Score: 0.9985

--------- Test ----------
Confusion Matrix:
[[12  0  0  0]
 [ 0  8  0  1]
 [ 0  0  5  1]
 [ 0  0  0  7]]

Accuracy: 0.9412
Precision: 0.9444
Recall: 0.9306
F1 Score: 0.9374


### 4. Load model

In [9]:
model = tf.keras.models.load_model(
    str(folder / 'experiments/2020-07-02-13-37-59/' / 'trained_model/air_multiclass_rnn/')
)
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 128, 401, 1)]     0         
_________________________________________________________________
Sequencer (SpectrogamSequenc multiple                  0         
_________________________________________________________________
time_distributed (TimeDistri multiple                  832       
_________________________________________________________________
Relu1 (Activation)           multiple                  0         
_________________________________________________________________
time_distributed_1 (TimeDist multiple                  0         
_________________________________________________________________
time_distributed_2 (TimeDist multiple                  25632     
_________________________________________________________________
Relu2 (Activation)           multiple                  0     

### 5. Evaluate model

In [10]:
model.evaluate(train_ds)

     14/Unknown - 1s 73ms/step - loss: 0.0566 - accuracy: 0.9977

[0.05664532578417233, 0.9977169]

In [11]:
model.evaluate(test_ds)

      1/Unknown - 0s 76ms/step - loss: 0.1798 - accuracy: 0.9706

[0.17982491850852966, 0.9705882]

In [12]:
display_performance(model, train_ds, test_ds)


------- Training --------
Confusion Matrix:
[[324   0   0   0]
 [  0 216   0   0]
 [  0   1 155   0]
 [  0   0   1 179]]

Accuracy: 0.9977
Precision: 0.9972
Recall: 0.9970
F1 Score: 0.9971

--------- Test ----------
Confusion Matrix:
[[12  0  0  0]
 [ 0  8  0  1]
 [ 0  0  6  0]
 [ 0  0  0  7]]

Accuracy: 0.9706
Precision: 0.9688
Recall: 0.9722
F1 Score: 0.9705
