###  Created by Luis A. Sanchez-Perez (alejand@umich.edu).
<p><span style="color:green"><b>Copyright &#169;</b> Do not distribute or use without authorization from author.</span></p>

In [1]:
import tensorflow as tf
import sys
sys.path.append('../extraction/')
sys.path.append('../models/')
from air_four_classes_temporal_cnn import create_dataset
from utils import display_performance
from commons import get_classes_from_directory

### 1. Create dataset

In [2]:
# Data location
folder = '../exports/2020-02-07 01-09-35 (four classes)/'

In [3]:
# Finding categories in the folder
classes = get_classes_from_directory(folder)
classes

[b'A320-2xx (CFM56-5)',
 b'B737-7xx (CF56-7B22-)',
 b'B737-8xx (CF56-7B22+)',
 b'ERJ190 (CF34-10E)']

In [4]:
train_ds, test_ds = create_dataset(folder, classes)

### 2. Load model

In [5]:
model = tf.keras.models.load_model(folder +
                                   'experiments/2020-07-01 22-06-25/' +
                                   'trained_model/air_four_classes_temporal_cnn/')

In [6]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 401, 128)]        0         
_________________________________________________________________
Conv1 (Conv1D)               (None, 51, 16)            32768     
_________________________________________________________________
BatchNorm1 (BatchNormalizati (None, 51, 16)            64        
_________________________________________________________________
activation (Activation)      (None, 51, 16)            0         
_________________________________________________________________
dropout (Dropout)            (None, 51, 16)            0         
_________________________________________________________________
Conv2 (Conv1D)               (None, 51, 16)            768       
_________________________________________________________________
BatchNorm2 (BatchNormalizati (None, 51, 16)            64    

### 3. Evaluate model

In [7]:
model.evaluate(train_ds)

     14/Unknown - 4s 264ms/step - loss: 0.2554 - accuracy: 0.9920

[0.25536510561193737, 0.9920091]

In [8]:
model.evaluate(test_ds)

      1/Unknown - 0s 102ms/step - loss: 0.5111 - accuracy: 0.9118

[0.5111063122749329, 0.9117647]

In [9]:
display_performance(model, train_ds, test_ds)


------- Training --------
Confusion Matrix:
[[324   0   0   0]
 [  0 214   0   2]
 [  0   1 154   1]
 [  0   3   0 177]]

Accuracy: 0.9920
Precision: 0.9912
Recall: 0.9903
F1 Score: 0.9908

--------- Test ----------
Confusion Matrix:
[[12  0  0  0]
 [ 0  7  1  1]
 [ 0  0  5  1]
 [ 0  0  0  7]]

Accuracy: 0.9118
Precision: 0.9028
Recall: 0.9028
F1 Score: 0.9028
