###  Created by Luis A. Sanchez-Perez (alejand@umich.edu).
<p><span style="color:green"><b>Copyright &#169;</b> Do not distribute or use without authorization from author.</span></p>

In [1]:
import tensorflow as tf
import pathlib
import sys
sys.path.append('../extraction/')
sys.path.append('../models/')
from air_multiclass_temporal_cnn import create_dataset
from utils import display_performance
from commons import get_classes_from_directory

### 1. Create dataset

In [2]:
# Data location
folder = pathlib.Path('../exports/2020-02-07 01-09-35 (four classes)/')

In [3]:
# Finding categories in the folder
classes = get_classes_from_directory(folder)
classes

[b'A320-2xx (CFM56-5)',
 b'B737-7xx (CF56-7B22-)',
 b'B737-8xx (CF56-7B22+)',
 b'ERJ190 (CF34-10E)']

In [4]:
train_ds, test_ds = create_dataset(folder, classes)

### 2. Load model

In [5]:
model = tf.keras.models.load_model(
    str(folder / 'experiments/2020-07-02-13-50-21' / 'trained_model/air_multiclass_temporal_cnn')
)

In [6]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 401, 128)]        0         
_________________________________________________________________
Conv1 (Conv1D)               (None, 51, 16)            32784     
_________________________________________________________________
Relu1 (Activation)           (None, 51, 16)            0         
_________________________________________________________________
dropout (Dropout)            (None, 51, 16)            0         
_________________________________________________________________
Conv2 (Conv1D)               (None, 51, 16)            784       
_________________________________________________________________
Relu2 (Activation)           (None, 51, 16)            0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 51, 16)            0     

### 3. Evaluate model

In [7]:
model.evaluate(train_ds)

     14/Unknown - 2s 152ms/step - loss: 0.1083 - accuracy: 0.9977

[0.10829956457018852, 0.9977169]

In [8]:
model.evaluate(test_ds)

      1/Unknown - 0s 85ms/step - loss: 0.4482 - accuracy: 0.8824

[0.448175311088562, 0.88235295]

In [9]:
display_performance(model, train_ds, test_ds)


------- Training --------
Confusion Matrix:
[[324   0   0   0]
 [  0 215   0   1]
 [  0   0 155   1]
 [  0   0   0 180]]

Accuracy: 0.9977
Precision: 0.9973
Recall: 0.9972
F1 Score: 0.9972

--------- Test ----------
Confusion Matrix:
[[12  0  0  0]
 [ 0  8  0  1]
 [ 0  1  3  2]
 [ 0  0  0  7]]

Accuracy: 0.8824
Precision: 0.8972
Recall: 0.8472
F1 Score: 0.8715
